# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 55a2a1b43abac0354753a9b149f21e476dd58f4cc907b97fa5f8e28f778c8dff427081999669871fb80ae12d4603bad528635b6f47c5ff5d461728e81197cf5e

test:
  secret_key_base: 471f0f5c1f2d41729e74675273cf3e5faf6ddfb4a8b7611a1e2dd5382eb439b3c9cebabe25b0b89b118b812effb409227ac3b8eae154dfd24bab6bfb92d8fe78

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
